### ISSUE TITLE
OpenCV does not longer install

### ISSUE THREAD

**Issue by PeterDHabermehl** [harbaum/tx-pi#15]
While trying out to create an image file, I just did a complete re-install on Raspbian stretch and found OpenCV installation failing, thus some Apps don't work / simply fail.

**Comment by heuer** [comment]
Which pip version (``pip -V``) are you using? I guess the pip shipped with Jessie (pip 1.5.6) is simply too old.

**Comment by PeterDHabermehl** [comment]
Updateing setuptools seemed to help - closed!
