### ISSUE TITLE
zbarlight does no longer install

### ISSUE THREAD

**Issue by PeterDHabermehl** [harbaum/tx-pi#16]
Checking the install log on **jessie**, I found that there is also an issue with the zbar installation.

Sorry for not having more information at the moment.

**Comment by heuer** [comment]
Cause of the problem: ``setuptools`` is outdated (version 5.5.1)
See <https://github.com/Polyconseil/zbarlight/issues/21>

With a more recent version (currently 40.8.0) the installation would work.

Maybe ``tx-pi-setup.sh`` should issue a 
``pip3 install -U setuptools`` 
command, too.

**Comment by harbaum** [comment]
Maybe we should move the whole tx-pi thing to the ftcommunity repo where everyone can easily work on it.

**Comment by PeterDHabermehl** [comment]
updating setuptools seems to help - done!

**Comment by heuer** [comment]
For documentation purposes: Fixed by <https://github.com/harbaum/tx-pi/commit/0e22e2b0c8988636f0768275bb67a107d6b0e72b>
