### ISSUE TITLE
Stretch: No splash screen

### ISSUE THREAD

**Issue by heuer** [harbaum/tx-pi#18]
Stretch shows no splash screen

**Comment by heuer** [comment]
Fixed this (not yet committed).
Unfortunately the splash screen does not work with Plymouth installed. Removing ``plymouth`` removes ``mountall``, too. 

Another solution might be a custom Plymouth theme.

I'll commit my solution. If it leads into trouble (acc. to my tests everything works) we may set ``ENABLE_SPLASH`` automatically to ``false`` iff Stretch is detected

**Comment by harbaum** [comment]
Back when i started this i had a lengthy fight with plymouth. In theory plymouth auto detects the right framebuffer. But there was a patch applied to plymouth at least in jessie which hard coded fb0. 

I finally ended up with the current solution.

It may be worth checking if plymouth in stretch still has this patch.

**Comment by heuer** [comment]
> It may be worth checking if plymouth in stretch still has this patch.

I'll try to find it. 

In the meantime I found a better solution than deinstalling plymouth: Masking the start service works, see 1040723f7496a524025c1893ef82cb2df48a7167
IMO that's acceptable

**Comment by heuer** [comment]
Due to c588d2df2ff94896dbd1774d0658af1e6bf3f497 the Stretch setup behaves almost identically to the Jessie setup (neither a service is masked nor a package is removed)
